// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionOrders.API.Data;

#nullable disable

namespace SolutionOrders.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514102829_AddRelations")]
    partial class AddRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionOrders.API.Models.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klienci");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Imie = "Jan",
                            Nazwisko = "Kowalski",
                            Telefon = "123456789"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.MetodaPlatnosci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktywna")
                        .HasColumnType("bit");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetodyPlatnosci");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Platnosc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Klient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kwota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Metoda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Platnosci");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.PozycjaWypozyczenia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaZaGodzine")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RowerId")
                        .HasColumnType("int");

                    b.Property<int>("WypozyczenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RowerId");

                    b.HasIndex("WypozyczenieId");

                    b.ToTable("PozycjeWypozyczenia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CenaZaGodzine = 15m,
                            RowerId = 1,
                            WypozyczenieId = 1
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Rower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rowery");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cena = 15m,
                            Nazwa = "Trek Marlin 5",
                            Status = "Dostępny",
                            Typ = "MTB"
                        },
                        new
                        {
                            Id = 2,
                            Cena = 12m,
                            Nazwa = "Kross Evado",
                            Status = "Dostępny",
                            Typ = "Trekking"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Serwis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OpisUsterki")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rower")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Serwisy");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.TypRoweru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypyRowerow");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Wypozyczenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataWypozyczenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataZwrotu")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.ToTable("Wypozyczenia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataWypozyczenia = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KlientId = 1,
                            Status = "Aktywne"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.PozycjaWypozyczenia", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Rower", "Rower")
                        .WithMany("PozycjeWypozyczenia")
                        .HasForeignKey("RowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionOrders.API.Models.Wypozyczenie", "Wypozyczenie")
                        .WithMany("PozycjeWypozyczenia")
                        .HasForeignKey("WypozyczenieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rower");

                    b.Navigation("Wypozyczenie");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Wypozyczenie", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Klient", "Klient")
                        .WithMany("Wypozyczenia")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Klient", b =>
                {
                    b.Navigation("Wypozyczenia");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Rower", b =>
                {
                    b.Navigation("PozycjeWypozyczenia");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Wypozyczenie", b =>
                {
                    b.Navigation("PozycjeWypozyczenia");
                });
#pragma warning restore 612, 618
        }
    }
}
